{% set version = "2.3.0" %}

package:
  name: pyshp
  version: {{ version }}

source:
  url: https://github.com/GeospatialPython/pyshp/archive/refs/tags/{{ version }}.tar.gz
  sha256: 8f482407d12ada3652de70f7ec07494047dc0766a1986e38506f1a24f6b07e0d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  source_files:
    - .
  requires:
    - pip
    - pytest
  imports:
    - shapefile
  commands:
    - pip check
    - python -c 'import shapefile; shapefile.test()'
    - pytest

about:
  home: https://pypi.python.org/pypi/pyshp
  license: MIT
  license_file: LICENSE.TXT
  summary: Pure Python read/write support for ESRI Shapefile format

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
