{% set version = "3.0.11" %}

package:
  name: pyshp
  version: {{ version }}

source:
  url: https://github.com/GeospatialPython/pyshp/archive/refs/tags/{{ version }}.tar.gz
  sha256: 3e46be10affe5f32f2289bba7ee9eb92b0e4af60765eee8e2356cbfd99cb9499

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  source_files:
    - .
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  imports:
    - shapefile
  commands:
    - pip check
    - pytest -k "not (test_reader_url)"

about:
  home: https://github.com/GeospatialPython/pyshp
  license: MIT
  license_file: LICENSE.TXT
  summary: Pure Python read/write support for ESRI Shapefile format

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
