{% set version = "2.2.0" %}

package:
  name: pyshp
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyshp/pyshp-{{ version }}.tar.gz
  sha256: 0eda209bd62f3345701c4f6799b638c114ceb67fee28295cddb4e1caf053e944

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - shapefile

about:
  home: https://pypi.python.org/pypi/pyshp
  license: MIT
  license_file: LICENSE.TXT
  summary: Pure Python read/write support for ESRI Shapefile format

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
