{% set version = "2.4.0" %}

package:
  name: pyshp
  version: {{ version }}

source:
  url: https://github.com/GeospatialPython/pyshp/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6abdd1b5ec05a42089a2864711b2eebd16501bf422296f4b8137e75d08ee19d5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  source_files:
    - .
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  imports:
    - shapefile
  commands:
    - pip check
    - python -c 'import shapefile; shapefile.test()'
    - pytest

about:
  home: https://pypi.python.org/pypi/pyshp
  license: MIT
  license_file: LICENSE.TXT
  summary: Pure Python read/write support for ESRI Shapefile format

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
