{% set version = "2.3.0" %}

package:
  name: pyshp
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyshp/pyshp-{{ version }}.tar.gz
  sha256: 825064ea403acf135e846cf8b0924499430e6be1cd37a0f34be7130906617d3c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - shapefile
  commands:
    - python -c 'import shapefile; shapefile.test()'

about:
  home: https://pypi.python.org/pypi/pyshp
  license: MIT
  license_file: LICENSE.TXT
  summary: Pure Python read/write support for ESRI Shapefile format

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
