{% set version = "2.3.1" %}

package:
  name: pyshp
  version: {{ version }}

source:
  url: https://github.com/GeospatialPython/pyshp/archive/refs/tags/{{ version }}.tar.gz
  sha256: b64f8ee95e86c9357fd4b730a5743a0adcdc40b498bf1d2ec3cbc10bf54e495e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  source_files:
    - .
  requires:
    - pip
    - pytest
  imports:
    - shapefile
  commands:
    - pip check
    - python -c 'import shapefile; shapefile.test()'
    - pytest

about:
  home: https://pypi.python.org/pypi/pyshp
  license: MIT
  license_file: LICENSE.TXT
  summary: Pure Python read/write support for ESRI Shapefile format

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
