schema_version: 1

context:
  version: "3.1.0"

package:
  name: pyshp
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pyshp/pyshp-${{ version }}.tar.gz
  sha256: 3f26a0a2bddaed5e0ae0b2fa37c327b09794a96f8a88e8f3fb41d73a1de08ec3

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports: shapefile
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pytest
        - hypothesis
    files:
      source:
        - .
    script:
      - pytest -k "not (test_reader_url)"

about:
  summary: Pure Python read/write support for ESRI Shapefile format
  license: MIT
  license_file: LICENSE.TXT
  homepage: https://pypi.org/project/pyshp/

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
